=== chandankumar7/XML/Q5/q3.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT payroll (Employee+)>
<!ELEMENT Employee (_10,Name,Department,Basicpay,Manager)>
<!ELEMENT _10 (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Department (#PCDATA)>
<!ELEMENT Basicpay (#PCDATA)>
<!ELEMENT Manager (#PCDATA)>

=== chandankumar7/XML/Q5/q3_ExternalDTD.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="q3.xsl"?>

<!DOCTYPE lib SYSTEM "q3.dtd">

<payroll>
    <Employee>
	    <_10>3215</_10>
		<Name>Tom</Name>
		<Department>Design</Department>
		<Basicpay>12000</Basicpay>
		<Manager>Richard West</Manager>
	</Employee>
	<Employee>
	    <_10>3228</_10>
		<Name>Jerry</Name>
		<Department>Design</Department>
		<Basicpay>9000</Basicpay>
		<Manager>Percy Jackson</Manager>
	</Employee>
</payroll>

=== chandankumar7/XML/Q5/q3.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="q3.xsl"?>
<!--
<!DOCTYPE lib SYSTEM "q3.dtd">
-->

<payroll xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="q3.xsd">
<!--<payroll>-->
    <Employee>
	    <_10>3215</_10>
		<Name>Tom</Name>
		<Department>Design</Department>
		<Basicpay>12000</Basicpay>
		<Manager>Richard West</Manager>
	</Employee>
	<Employee>
	    <_10>3228</_10>
		<Name>Jerry</Name>
		<Department>Design</Department>
		<Basicpay>9000</Basicpay>
		<Manager>Percy Jackson</Manager>
	</Employee>
</payroll>
