=== chandankumar7/XML/Q2/q2.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">
<xs:element name="catalog">
    <xs:complexType>
	    <xs:sequence>
	        <xs:element name="cd" maxOccurs="unbounded">
		        <xs:complexType>
			        <xs:sequence>
		                <xs:element name="title" type="xs:string"/>
		                <xs:element name="artist" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
		                <xs:element name="company" type="xs:string"/>
		                <xs:element name="price" type="xs:float"/>
						<xs:element name="year_of_release" type="xs:integer"/>
		            </xs:sequence>
		        </xs:complexType>
		    </xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== chandankumar7/XML/Q2/q2_XSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="q2.xsl"?>

<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="q2.xsd">

    <cd>
	<title>Traveling Riverside Blues</title>
	<artist>Led Zeppelin</artist>
	<company>Warner music group</company>
	<price>40</price>
	<year_of_release>1969</year_of_release>
	</cd>
	
	<cd>
	<title>A Brand New Day</title>
	<artist>Michael Jackson</artist>
	<company>South Korean</company>
	<price>13.42</price>
	<year_of_release>1978</year_of_release>
	</cd>
	
	
	<cd>
	<title>The Dark Side of the Moon</title>
	<artist>Pink Floyd</artist>
	<company>Columbia</company>
	<price>14.3</price>
	<year_of_release>1985</year_of_release>
	</cd>

</catalog>
